version: '3.1'
services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong

  kong:
    image: kong:0.10
    links:
      - database:database.service.kong.internal
    environment:
      - KONG_PG_HOST=database.service.kong.internal
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    restart: on-failure:5
